apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-test-2-config
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
        location /health {
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }