apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-2
  namespace: nginx-test-2
  labels:
    app: nginx-test-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test-2
  template:
    metadata:
      labels:
        app: nginx-test-2
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        env:
        - name: NGINX_PORT
          value: "80"