---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: kube-system
spec:
  encryptedData:
    token: AgBgjZvEO6JNIO90gONhWbUnZ4UzTH3hpHK5bDGaclF8GmbplgyCmB+n2G1nHeGDTL3tQOk/Vmmp6b7Y3vDeB/nwyBVktghvAmdEZyPzqraBXj10+8eOodM3kdBrNGa03i8qAi/SCEe4W3majv2kNxj9fqVeKQ165EHxObxUekVeexxcdSNaZ7JHJuUl5EOXzm5+7KjemlWad4EZjZs6yiXgrRQhHkq87syp4OyyPepNrGZeVi/JphXM/VPWdwCgJfZJSFh9C80dt84+TVK6sbY2G/8qnDJjyMye1/xUInOh4wkcpiD5ddAPyHTpXj4LQmZH6lwyREWn47PMtf/933uL/CkSRLbFU3jk1tAkpEhUEkCgQ6poGEU+VHbHS4GrzKpJXjToHSF8I5h+Mxb+GJRtb7p7NBUR4kO49G1ZW1O34j6j/0Ug68UpekmKpKUCNfsSha0UF77dFhveHv5dIX7qom+DVt8WgI6SaB3Z0HLGMimXLI7hIo5gWTyy1YmarGUZJmuOrABB5/kjPlG1QShfgWUdf9qjj0M/0J3ViabmJfXMn/sdW1EV/cY+HUAt3Fug2qCcxC0cTBlvNFfToqGawlQp451EHvcO/Ebl1+wq+/iJb85L4JIQBfqEtH1DgLlFvB1YwW2T8dPeHbG9gO67bqkup5wvbj24stNrW4gWaPW7xjWRtHQ/zjJUk1cdi1/aKzbJosacmnz6NkUnbB4BWKgHglLuzaLpMuKGjML5n7LgVzWmjS7KcKmKvhNk5Hw+EJ9AhXSEJDfWbantnKzLwxWbdnwgirz/c7cFFZeGFzIvtNEiDskBKXPf/BiEQ4cDC0qcfSoUWwoLeYAsGkn+lKQialhFAuitowcfzpOvPvXrMy0hr9vXdo+19LD9l/qnaXKikTIf+YB6u7ajKZx63eNz8+GVPcqPVqXBTMGnW3JZUkc=
  template:
    metadata:
      name: tunnel-credentials
      namespace: kube-system
