apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-data
  namespace: crafty-controller
  labels:
    app.kubernetes.io/name: crafty-controller
    app.kubernetes.io/part-of: homelab
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
