apiVersion: v1
kind: ConfigMap
metadata:
  name: example-app
  labels:
    app.kubernetes.io/name: example-app
spec:
  # This is a placeholder app directory
  # Add your actual application manifests here
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-nginx-service
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP