apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-generator
spec:
  generators:
  # Generator for apps/ directories
  - git:
      repoURL: &repoURL https://github.com/bartlomiej-kochanowicz/homelab.git
      revision: HEAD
      directories:
      - path: apps/*
  # Generator for system/ directories (excluding argocd to prevent recursion)
  - git:
      repoURL: *repoURL
      revision: HEAD
      directories:
      - path: system/*
      - path: system/argocd
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        app.kubernetes.io/managed-by: apps-generator
        app.kubernetes.io/part-of: homelab
        environment: test
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: *repoURL
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
      revisionHistoryLimit: 3